
from linked_list import Node, LinkedList

def main():
    lis = LinkedList()
    lis.add(1)
    print_list(lis)
    lis.add_last(3)
    print_list(lis)
    lis.add(5)
    print_list(lis)
    lis.add(7)
    print_list(lis)
    lis.add(9)
    print_list(lis)
    lis.add_first(0)
    print_list(lis)
    lis.add(2,2)
    print_list(lis)
    lis.add(4,4)
    print_list(lis)
    lis.add(6,6)
    print_list(lis)
    lis.add(8,8)
    print_list(lis)
    lis.add_last(10)
    print_list(lis)
    print('remove ' + str(lis.remove(2)))
    print_list(lis)
    print('remove ' + str(lis.remove(1)))
    print_list(lis)
    print('remove ' + str(lis.remove_first()))
    print_list(lis)
    print('remove ' + str(lis.remove(0)))
    print_list(lis)
    print('remove ' + str(lis.remove(4)))
    print_list(lis)
    print('remove ' + str(lis.remove(2)))
    print_list(lis)
    print('remove ' + str(lis.remove_last()))
    print_list(lis)
    print('remove ' + str(lis.remove(1)))
    print_list(lis)
    print('remove ' + str(lis.remove()))
    print_list(lis)
    print('remove ' + str(lis.remove(0)))
    print_list(lis)
    print('remove ' + str(lis.remove_last()))
    print_list(lis)
    print('remove ' + str(lis.remove_last()))
    print_list(lis)


def print_list(lis):
    print(str(lis) + '\t head: ' + str(lis.head) + "\t tail: " + str(lis.tail) + "\t length: " + str(lis.length))


if __name__ == '__main__':
    main()